name: flutter_colorgen
description: Flutter color pickers examples

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  color: "^2.0.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true